name: communication-control-project

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    networks:
      - net1

  comm:
    build:
      context: ./src/CommunicationControl/DevOpsProject
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - Redis_ConnectionString=redis:6379
    depends_on:
      - redis
    networks:
      - net1

  hive:
    build:
      context: ./src/CommunicationControl/DevOpsProject.HiveMind.API
      dockerfile: Dockerfile
    ports:
      - "5149:5149"
    environment:
      - CommunicationConfiguration__CommunicationControlIP=comm
      - CommunicationConfiguration__CommunicationControlPort=8080
      - CommunicationConfiguration__RequestSchema=http
      - CommunicationConfiguration__CommunicationControlPath=api/v1/hive
      - CommunicationConfiguration__HiveIP=hive
      - CommunicationConfiguration__HivePort=5149
      - CommunicationConfiguration__HiveID=1
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - comm
    networks:
      - net1

  web:
    build: ./src/MapClient
    ports:
      - "80:80"
    stdin_open: true
    tty: true
    networks:
      - net1

networks:
  net1:
    driver: bridge